openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8888'
    description: Generated server url
paths:
  /calculate:
    post:
      tags:
        - calculator-controller
      operationId: calculate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Result'
components:
  schemas:
    Input:
      type: object
      properties:
        category:
          type: string
        value:
          type: integer
          format: int64
    Result:
      type: object
      properties:
        category:
          type: string
        duration:
          type: integer
          format: int64
        index:
          type: integer
          format: int64
