openapi: 3.0.1
info:
  title: Daily Calculator Service
  version: v0
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
paths:
  '/context/{date}/calculate':
    post:
      tags:
        - DailyCalculatorService
      summary: triggers a calculation
      description: This operation should just trigger the calculation and not wait for the result
      operationId: calculate
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Input'
            example:
              category: "beta-build"
              value: 7762
        required: true
      responses:
        '200':
          description: calculation request received
        '400':
          description: execution against a closed context
  '/context/{date}/close':
    post:
      tags:
        - DailyCalculatorService
      summary: closes a context
      description: All previously triggered calculations for this context need to be included in the result
      operationId: close
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContextStatus'
              example:
                sum: 232399
                count: 48
        '400':
          description: execution against a closed context
        '404':
          description: context not found
  '/context/{date}':
    delete:
      tags:
        - DailyCalculatorService
      summary: deletes a context
      operationId: delete
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: successful deletion
        '404':
          description: context not found
components:
  schemas:
    Input:
      type: object
      properties:
        category:
          type: string
        value:
          type: integer
          format: int64
    ContextStatus:
      type: object
      properties:
        sum:
          type: integer
          format: int64
        count:
          type: integer
          format: int32
